apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: hello2
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 0
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: nodejsv2
    namespace: default
  functionTimeout: 60
  package:
    functionName: helloworld
    packageref:
      name: dummy-2
      namespace: default
  resources: {}
  secrets: null
