apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: dummy-1
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: https://raw.githubusercontent.com/fission/fission/master/examples/nodejs/hello.js
  environment:
    name: nodejs
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2019-11-16T13:58:58.508922Z"
